<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Image Maker</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      text-align: center;
      background-color: #f3f3f3;
      margin: 0;
      padding: 20px;
    }

    .container {
      margin: auto;
      width: 90%;
      max-width: 600px;
      background: white;
      border-radius: 10px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
      padding: 20px;
    }

    canvas {
      border: 1px solid #ddd;
      margin: 20px 0;
    }

    input[type="file"], input[type="text"], button {
      margin: 10px;
      padding: 10px;
      border-radius: 5px;
      border: 1px solid #ccc;
      width: calc(100% - 24px);
    }

    button {
      background-color: #007BFF;
      color: white;
      cursor: pointer;
    }

    button:hover {
      background-color: #0056b3;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Image Maker</h1>
    <input type="file" id="imageUpload" accept="image/*">
    <canvas id="canvas"></canvas>
    <input type="text" id="textInput" placeholder="Enter text here">
    <button id="downloadBtn">Download</button>
  </div>

  <script>
    const imageUpload = document.getElementById('imageUpload');
    const textInput = document.getElementById('textInput');
    const downloadBtn = document.getElementById('downloadBtn');
    const canvas = document.getElementById('canvas');
    const ctx = canvas.getContext('2d');
    let img = null;

    imageUpload.addEventListener('change', (event) => {
      const file = event.target.files[0];
      const reader = new FileReader();

      reader.onload = (e) => {
        img = new Image();
        img.src = e.target.result;
        img.onload = () => {
          canvas.width = img.width;
          canvas.height = img.height;
          ctx.drawImage(img, 0, 0);
        };
      };

      reader.readAsDataURL(file);
    });

    textInput.addEventListener('input', () => {
      if (img) {
        ctx.drawImage(img, 0, 0);
        ctx.font = '40px Arial';
        ctx.fillStyle = 'red';
        ctx.fillText(textInput.value, 20, 50);
      }
    });

    downloadBtn.addEventListener('click', () => {
      const link = document.createElement('a');
      link.download = 'image.png';
      link.href = canvas.toDataURL();
      link.click();
    });
  </script>
</body>
</html>
